name: hello-workflow

on:
  schedule:
    - cron:  "*/5 * * * *" # Every 5 minutes

jobs:
  update-packages:
    name: update packages

    runs-on: ubuntu-latest

    steps:
      - name: hello
        run: echo "Hello World"