name: Update npm packages

on:
  workflow_dispatch:

  schedule:
    - cron:  "14 3 * * 1" # At 03:14 on Monday

jobs:
  update-packages:
    name: update packages

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: update packages
        run: npm update --save

      - name: Commit and create PR
        uses: peter-evans/create-pull-request@v6
        with:
          title: 'Update npm packages'
          branch: 'npm-update-job'
          commit-message: 'Update npm packages'